### ISSUE TITLE
	c.String(200, c.Param("id"))  return empty 

### ISSUE THREAD

**Issue by tablecell** [go-baa/baa#6]
````
  app.Get("/view-:id(\\d+)", func(c *baa.Context) {
		c.String(200, c.Param("id"))
	})

````
curl http://localhost:1234/view-111
return empty

**Comment by safeie** [comment]
default route cannot match the path divide without /, if you want match any character path, please use regexp route,
please view document,

https://github.com/go-baa/doc/blob/master/zh-CN/router.md#正则路由
